#!/bin/sh

set -e

case "$1" in
    configure)
    update-pepperflashplugin-adobe-nonfree --install
    if hash systemctl
    then
        systemctl enable pepperflash-adobe.timer
        systemctl start pepperflash-adobe.timer
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


