#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
    if hash systemctl
    then
        systemctl stop pepperflash-adobe.timer
        systemctl disable pepperflash-adobe.timer
    fi
    update-pepperflashplugin-adobe-nonfree --uninstall
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


